# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'dsptreg'
    repository: 'dsptapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
    
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Free Trial(0d119fa6-53bc-4568-8d4d-28e6aa7ad897)'
    Action: 'Stop Azure App Service'
    WebAppName: 'dsptappmongo'
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(0d119fa6-53bc-4568-8d4d-28e6aa7ad897)'
    appType: 'webAppContainer'
    WebAppName: 'dsptappmongo'
    DockerNamespace: 'dsptnehareg.azurecr.io'
    DockerRepository: 'dsptapp'
    DockerImageTag: 'latest'
    
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Free Trial(0d119fa6-53bc-4568-8d4d-28e6aa7ad897)'
    Action: 'Start Azure App Service'
    WebAppName: 'dsptappmongo'
    
- script: |
    python3 -m pip install --upgrade pip
    pip install pytest
  displayName: 'Install dependencies'

- script: |
    python3 -m pytest unit_test.py
  displayName: 'pytest'    
