# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    python --version
    sudo apt-get update
    sudo apt-get install python3.6
    python --version
    pip install --upgrade pip
    pip install -U pytest
    pytest --version
  displayName: 'Install dependencies'

- script: |
    pytest '**/unit_test.py'
  displayName: 'pytest'    
