# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'dsptreg'
    repository: 'dsptapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
    
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'dsptreg_armsc'
    Action: 'Stop Azure App Service'
    WebAppName: 'dsptappmongodev'
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'dsptreg_armsc'
    appType: 'webAppContainer'
    WebAppName: 'dsptappmongodev'
    DockerNamespace: 'dsptreg.azurecr.io'
    DockerRepository: 'dsptapp'
    DockerImageTag: 'latest'
    
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'dsptreg_armsc'
    Action: 'Start Azure App Service'
    WebAppName: 'dsptappmongodev'